name: py3_parcels
channels:
  - defaults
  - conda-forge
dependencies:
  - cachetools>=1.0.0
  - cftime>=1.3.1
  - cgen
  - coverage
  - dask>=2.0
  - ffmpeg>=3.2.3
  - flake8>=2.1.0
  - gcc_linux-64
  - git
  - hdf5>=1.10.6
  - jupyter
  - mpi4py>=3.0.1
  - mpich>=3.2.1
  - matplotlib>=2.0.2
  - netcdf4>=1.1.9
  - nbval
  - numpy>=1.9.1
  - pandas>=0.19.2,<1.3.0
  - progressbar
  - py>=1.4.27
  - pykdtree
  - pymbolic
  - pytest2
  - python>=3.4
  - python-dateutil
  - scipy>=0.16.0
  - scikit-learn
  - six>=1.10.0
  - sortedcontainers>=2.1.0
  - xarray>=0.10.8
