name: py3_parcels
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - cgen
  - coverage
  - ffmpeg>=3.2.3
  - flake8>=2.1.0
  - git
  - gcc_linux-64
  - mpi4py>=3.0.1
  - mpich>=3.2.1
  - jupyter
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - psutil
  - py>=1.4.27
  - pymbolic
  - scipy>=0.16.0
  - tqdm
  - xarray>=0.10.8
  - cftime>=1.3.1
  - dask>=2.0
  - pytest
  - nbval
  - scikit-learn
  - pykdtree
  - zarr
